[2024-05-01T17:59:47.047+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.insert_table manual__2024-05-01T17:59:28.974851+00:00 [queued]>
[2024-05-01T17:59:47.068+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.insert_table manual__2024-05-01T17:59:28.974851+00:00 [queued]>
[2024-05-01T17:59:47.068+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 4
[2024-05-01T17:59:47.136+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): insert_table> on 2024-05-01 17:59:28.974851+00:00
[2024-05-01T17:59:47.141+0000] {standard_task_runner.py:60} INFO - Started process 121 to run task
[2024-05-01T17:59:47.145+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'main_dag', 'insert_table', 'manual__2024-05-01T17:59:28.974851+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp1myiwz6k']
[2024-05-01T17:59:47.150+0000] {standard_task_runner.py:88} INFO - Job 28: Subtask insert_table
[2024-05-01T17:59:47.264+0000] {task_command.py:423} INFO - Running <TaskInstance: main_dag.insert_table manual__2024-05-01T17:59:28.974851+00:00 [running]> on host 54fd76cc0661
[2024-05-01T17:59:47.410+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='insert_table' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T17:59:28.974851+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T17:59:28.974851+00:00'
[2024-05-01T17:59:48.040+0000] {logging_mixin.py:188} INFO - An error occured: [Errno 2] No such file or directory: 'trip_data_query.sql'
[2024-05-01T17:59:48.042+0000] {logging_mixin.py:188} INFO - An error occured: 'NoneType' object is not iterable
[2024-05-01T17:59:48.043+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-05-01T17:59:48.057+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=insert_table, execution_date=20240501T175928, start_date=20240501T175947, end_date=20240501T175948
[2024-05-01T17:59:48.151+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-01T17:59:48.184+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
